### ISSUE TITLE
DOCS_STATUS not being used

### ISSUE THREAD

**Issue by bmorcos** [nengo/nengo-bones#62]
I've been messing around trying to get `nengo-fpga` docs to build on a remote server and noticed that the `DOCS_STATUS` flag isn't persistent since each script section (eg. `./.ci/docs.sh after_script`) is run separately.

The `DOCS_STATUS` flag gets set after building the docs, but before link checks in the [script section](https://github.com/nengo/nengo-bones/blob/master/nengo_bones/templates/docs.sh.template#L27) and then it gets used for conditional execution in the [after_script section](https://github.com/nengo/nengo-bones/blob/master/nengo_bones/templates/docs.sh.template#L33)

In my experience it seems that the `DOCS_STATUS` flag in the `after_script` section is undefined (since each script section is a separate command), so this condition is likely never being triggered.

@drasmuss notes that the idea of putting this in `after_script` instead of `after_success` is to allow docs to build even if linkcheck fails such that we can inspect `gh-pages-test` (65d0b5401af7d1d2a40e28ebd88518ebc818d0c3)

**Comment by drasmuss** [comment]
Results of internal discussion: The current behaviour is pretty much what we want. It's not ideal, since it's possible to accidentally upload a failing doc build, but that requires the merger to ignore a bunch of errors in the build log before merging it into master. And there doesn't seem to be a clean way to safeguard against that. So we're just going to remove the `DOCS_STATUS` logic, and leave the current behaviour as is.
